accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('follow/<int:user_id>/', views.FollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>/', views.UnFollowView.as_view(), name='unfollow'),
    path('profile_edit/<int:user_id>/', views.UserInfoEditView.as_view(), name='profile_edit'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed

app_name = 'social'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('page/<int:pnum>/', views.HomeView.as_view(), name='home'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<slug:slug>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='detail'),
    path('comment_reply/<slug:post_slug>/<int:comment_id>/', views.CommentReplyView.as_view(), name='cmreply'),
    path('like/<slug:post_slug>/', views.LikePostView.as_view(), name='like_post'),
    path('search', views.SearchView.as_view(), name='search'),
    path('followingfeed/', views.FollowingFeedView.as_view(), name='followingfeed'),
    path('latestfeed/', LatestEntriesFeed(), name='rssfeed'),
]

social/models.py
from django.db import models
from accounts.models import User
from django.utils.html import format_html
from django.urls import reverse
from django.template.defaultfilters import slugify


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255, unique=True)
    body = models.TextField()
    slug = models.SlugField()
    img = models.ImageField(upload_to='posts/%Y/%m/%d/',)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def thumbnail(self):
        return format_html(f"<img width=100 height=45 style='border-radius: 5px;' src='{self.img.url}'>")

    def trunc_title(self):
        return self.title[:30] + ' ...'
    trunc_title.short_description = 'Title'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('social:detail', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title[:20])
        return super().save(*args, **kwargs)

    def like_count(self):
        return self.likepost.count()

    def like_existance(self, user):
        return Like.objects.filter(user=user, post=self).exists()


    class Meta:
        ordering = ('-created',)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likeuser')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likepost')

    def __str__(self):
        return f'{self.user} Liked {self.post.title[:20]}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usercm')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postcm')
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user} on {self.post}'

    class Meta:
        ordering = ('-created',)

social/forms.py
from django import forms
from .models import Post, Comment
from django.core.exceptions import ValidationError

class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'img')

    def clean_title(self):
        title = self.cleaned_data.get("title")
        title_exists = Post.objects.filter(title=title).exists()
        if title_exists:
            raise ValidationError('title exists')
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from accounts.models import User, FollowRelation
from .models import Post, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.contrib import messages
from .forms import PostCreateUpdateForm, CommentForm, CommentReplyForm
from django.db.models import Q
from django.core.paginator import Paginator


class HomeView(View):

    def get(self, request, pnum=1):
        posts = Post.objects.all()
        paginator = Paginator(posts, 3)
        page_number = pnum
        posts = paginator.get_page(page_number)
        return render(request, 'social/home.html', {'posts':posts})


class SearchView(View):

    def get(self, request):
        q = request.GET.get('q')
        if q:
            constraint = Q(body__icontains=q) | Q(title__icontains=q) | Q(user__username__icontains=q)
            posts = Post.objects.filter(constraint)
            paginator = Paginator(posts, 2)
            page_number = request.GET.get('page')
            posts = paginator.get_page(page_number)
        return render(request, 'social/home.html', {'posts':posts})


class ProfileView(LoginRequiredMixin, View):

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        relation = FollowRelation.objects.filter(follower=request.user.id, followed=user).exists()
        posts = user.posts.all()
        return render(request, 'social/profile.html', {'user':user, 'posts':posts, 'relation':relation})


class FollowingFeedView(LoginRequiredMixin, View):
    def get(self, request):
        relations = request.user.followers.all()
        users = [user.followed for user in relations]
        posts = Post.objects.filter(user__in=users)
        return render(request, 'social/home.html', {'posts':posts})


class PostDetailView(View):
    form_class = CommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'You must be logged in', 'danger')
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        like_existance = self.post_instance.like_existance(user=request.user)
        return render(request, 'social/detail.html',
                      {'post':self.post_instance, 'form':form,
                       'reply_form':self.form_class_reply, 'like_existance':like_existance,
                       })

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cm = form.save(commit=False)
            cm.user = request.user
            cm.post = self.post_instance
            cm.save()
            messages.success(request, 'comment added successfully', 'success')
            return redirect(self.post_instance.get_absolute_url())
        return render(request, 'social/detail.html', {'post':self.post_instance, 'form':form})


class PostDeleteView(View):

    def dispatch(self, request, *args, **kwargs):
        self.post = get_object_or_404(Post, slug=kwargs.get('slug'))
        author = self.post.user
        if author != request.user:
            messages.error(request, 'You are not allowed to delete this post', 'danger')
            return redirect(self.post.get_absolute_url())
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, slug):
        self.post.delete()
        return redirect('social:profile', username=request.user.username)


class PostCreateView(LoginRequiredMixin ,View):
    form_class = PostCreateUpdateForm
    template_name = 'social/create_post.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Post created successfully', 'success')
            return redirect(post.get_absolute_url())
        return render(request, self.template_name, {'form': form})


class PostUpdateView(LoginRequiredMixin ,View):
    form_class = PostCreateUpdateForm
    template_name = 'social/update_post.html'

    def dispatch(self, request, *args, **kwargs):
        self.instance = get_object_or_404(Post, slug=kwargs.get('slug'))
        author = self.instance.user
        if author != request.user:
            messages.error(request, 'You are not allowed to update this post', 'danger')
            return redirect(self.instance.get_absolute_url())
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, slug):
        form = self.form_class(instance=self.instance)
        return render(request, self.template_name, {'form': form})

    def post(self, request, slug):
        form = self.form_class(request.POST, request.FILES, instance=self.instance)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Post updated successfully', 'success')
            return redirect(post.get_absolute_url())
        return render(request, self.template_name, {'form': form})


class CommentReplyView(LoginRequiredMixin , View):
    form_class = CommentReplyForm

    def post(self, request, post_slug, comment_id):
        form = self.form_class(request.POST)
        post_instance = get_object_or_404(Post, slug=post_slug)
        if form.is_valid():
            cm = form.save(commit=False)
            cm.user = request.user
            cm.post = post_instance
            cm.reply = get_object_or_404(Comment, id=comment_id)
            cm.is_reply = True
            cm.save()
            messages.success(request, 'Comment created successfully', 'success')
            return redirect(post_instance.get_absolute_url())
        return render(request, 'social/detail.html', {'form':form})


class LikePostView(LoginRequiredMixin , View):

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user == self.post_instance.user:
            raise ValidationError('You cant like yourself')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        like = Like.objects.filter(user=request.user, post=self.post_instance)
        if not like.exists():
            Like.objects.create(user=request.user, post=self.post_instance)
        else:
            like.delete()
        return redirect(self.post_instance.get_absolute_url())

social/templates/social/inc/footer.html
{% load static %}

<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">

        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Agency</h6>
                    <p>
                        The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point
                    </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Navigation Links</h6>
                    <div class="row">
                        <div class="col">
                            <ul>
                                <li><a href="{% url 'social:home' %}">Home</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
</footer>
<!-- End footer Area -->
        <script src="{% static 'social/js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'social/js/popper.min.js' %}"></script>
        <script src="{% static 'social/js/vendor/bootstrap.min.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
        <script src="{% static 'social/js/jquery-ui.js' %}"></script>
        <script src="{% static 'social/js/easing.min.js' %}"></script>
        <script src="{% static 'social/js/hoverIntent.js' %}"></script>
        <script src="{% static 'social/js/superfish.min.js' %}"></script>
        <script src="{% static 'social/js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'social/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'social/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'social/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'social/js/mail-script.js' %}"></script>
        <script src="{% static 'social/js/main.js' %}"></script>

social/templates/social/inc/header.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Django Social Network</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--
        CSS
        ============================================= -->
        <link rel="stylesheet" href="{% static  'social/css/linearicons.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/font-awesome.min.css' %}" >
        <link rel="stylesheet" href="{% static  'social/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static  'social/css/main.css' %}">
    </head>
    <body>
        <header id="header">
            </div>
            <div class="container main-menu">
                <div class="row align-items-center justify-content-between d-flex">
                  <div id="logo">
                    <a href="#"><img style="max-width: 200px; max-height: 70px; border-radius: 50%;" src="{% static 'social/img/logo.png' %}" alt="" title="" /></a>
                  </div>
                  <nav id="nav-menu-container">
                    <ul class="nav-menu">
                      <li><a href="{% url 'social:home' %}">Home</a></li>
                      {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:login' %}">Login</a>/<a href="{% url 'accounts:signup' %}">Signup</a></li>
                      {% else %}
                        <li><a href="{% url 'social:profile' request.user.username %}">Profile</a>
                        <li><a href="{% url 'social:followingfeed' %}">Followings posts</a>
                        <li><a href="{% url 'social:post_create' %}">Create Post</a>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a>
                      {% endif %}
                        <li><a href="{% url 'social:rssfeed' %}">RSSfeed</a></li>
                    </ul>
                  </nav><!-- #nav-menu-container -->
                </div>
            </div>
        </header><!-- #header -->

social/templates/social/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

social/templates/social/inc/widget-latestpost.html
{% load static %}
{% load humanize %}
{% load inclusion_tags %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in latest_posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" style="max-width: 100px; " src={{post.img.url}} alt="">
            </div>
            <div class="details">
                <a href="{% url 'social:detail' post.slug %}"><h6>{{post.title|truncatewords:3}}</h6></a>
                <p>{{post.user}}</p>
                <p>{{post.created|naturaltime}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

social/templates/social/inc/widget-search.html
{% load static %}

<div class="single-sidebar-widget search-widget">
    <form method="GET" class="search-form" action="{% url 'social:search' %}" >
        <input placeholder="Search Posts" value="{{ request.GET.q }}" name="q" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

social/templates/social/inc/widget-writer.html
{% load static %}

<div class="single-sidebar-widget user-info-widget">
    <img style="max-width: 200px; border-radius: 50%;" src="{{user.img.url}}" alt="">
    <a href="{% url 'social:profile' user.username %}"><h4>{{user.get_full_name}}</h4></a>
    <p class="view col-lg-12 col-md-12 col-6"> <span class="lnr lnr-user"></span> <a href="#">{{user.followings.count}} Follower</a></p>
    <p>
        {{user.bio|safe}}
    </p>
    {% if request.user != user %}
    <ul class="social-links">
        {% if not relation %}
        <li><a href="{% url 'accounts:follow' user.id %}"><i class="btn btn-info"> Follow </i></a></li>
        {% else %}
        <li><a href="{% url 'accounts:unfollow' user.id %}"><i class="btn btn-danger"> Unfollow </i></a></li>
        {% endif %}
    {% else %}
        <a href="{% url 'accounts:profile_edit' user.id %}"><i class="btn btn-info"> Edit profile </i></a>
    </ul>
    {% endif %}
</div>