config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed

app_name = 'social'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('page/<int:pnum>/', views.HomeView.as_view(), name='home'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<slug:slug>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='detail'),
    path('comment_reply/<slug:post_slug>/<int:comment_id>/', views.CommentReplyView.as_view(), name='cmreply'),
    path('like/<slug:post_slug>/', views.LikePostView.as_view(), name='like_post'),
    path('search', views.SearchView.as_view(), name='search'),
    path('followingfeed/', views.FollowingFeedView.as_view(), name='followingfeed'),
    path('latestfeed/', LatestEntriesFeed(), name='rssfeed'),
]

social/models.py
from django.db import models
from accounts.models import User
from django.utils.html import format_html
from django.urls import reverse
from django.template.defaultfilters import slugify


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255, unique=True)
    body = models.TextField()
    slug = models.SlugField()
    img = models.ImageField(upload_to='posts/%Y/%m/%d/',)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def thumbnail(self):
        return format_html(f"<img width=100 height=45 style='border-radius: 5px;' src='{self.img.url}'>")

    def trunc_title(self):
        return self.title[:30] + ' ...'
    trunc_title.short_description = 'Title'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('social:detail', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title[:20])
        return super().save(*args, **kwargs)

    def like_count(self):
        return self.likepost.count()

    def like_existance(self, user):
        return Like.objects.filter(user=user, post=self).exists()


    class Meta:
        ordering = ('-created',)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likeuser')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likepost')

    def __str__(self):
        return f'{self.user} Liked {self.post.title[:20]}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usercm')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postcm')
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user} on {self.post}'

    class Meta:
        ordering = ('-created',)

social/forms.py
from django import forms
from .models import Post, Comment
from django.core.exceptions import ValidationError

class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'img')

    def clean_title(self):
        title = self.cleaned_data.get("title")
        title_exists = Post.objects.filter(title=title).exists()
        if title_exists:
            raise ValidationError('title exists')
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from accounts.models import User, FollowRelation
from .models import Post, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.contrib import messages
from .forms import PostCreateUpdateForm, CommentForm, CommentReplyForm
from django.db.models import Q
from django.core.paginator import Paginator


class HomeView(View):

    def get(self, request, pnum=1):
        posts = Post.objects.all()
        paginator = Paginator(posts, 3)
        page_number = pnum
        posts = paginator.get_page(page_number)
        return render(request, 'social/home.html', {'posts':posts})


class SearchView(View):

    def get(self, request):
        q = request.GET.get('q')
        if q:
            constraint = Q(body__icontains=q) | Q(title__icontains=q) | Q(user__username__icontains=q)
            posts = Post.objects.filter(constraint)
            paginator = Paginator(posts, 2)
            page_number = request.GET.get('page')
            posts = paginator.get_page(page_number)
        return render(request, 'social/home.html', {'posts':posts})


class ProfileView(LoginRequiredMixin, View):

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        relation = FollowRelation.objects.filter(follower=request.user.id, followed=user).exists()
        posts = user.posts.all()
        return render(request, 'social/profile.html', {'user':user, 'posts':posts, 'relation':relation})


class FollowingFeedView(LoginRequiredMixin, View):
    def get(self, request):
        relations = request.user.followers.all()
        users = [user.followed for user in relations]
        posts = Post.objects.filter(user__in=users)
        return render(request, 'social/home.html', {'posts':posts})


class PostDetailView(View):
    form_class = CommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'You must be logged in', 'danger')
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        like_existance = self.post_instance.like_existance(user=request.user)
        return render(request, 'social/detail.html',
                      {'post':self.post_instance, 'form':form,
                       'reply_form':self.form_class_reply, 'like_existance':like_existance,
                       })

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cm = form.save(commit=False)
            cm.user = request.user
            cm.post = self.post_instance
            cm.save()
            messages.success(request, 'comment added successfully', 'success')
            return redirect(self.post_instance.get_absolute_url())
        return render(request, 'social/detail.html', {'post':self.post_instance, 'form':form})


class PostDeleteView(View):

    def dispatch(self, request, *args, **kwargs):
        self.post = get_object_or_404(Post, slug=kwargs.get('slug'))
        author = self.post.user
        if author != request.user:
            messages.error(request, 'You are not allowed to delete this post', 'danger')
            return redirect(self.post.get_absolute_url())
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, slug):
        self.post.delete()
        return redirect('social:profile', username=request.user.username)


class PostCreateView(LoginRequiredMixin ,View):
    form_class = PostCreateUpdateForm
    template_name = 'social/create_post.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Post created successfully', 'success')
            return redirect(post.get_absolute_url())
        return render(request, self.template_name, {'form': form})


class PostUpdateView(LoginRequiredMixin ,View):
    form_class = PostCreateUpdateForm
    template_name = 'social/update_post.html'

    def dispatch(self, request, *args, **kwargs):
        self.instance = get_object_or_404(Post, slug=kwargs.get('slug'))
        author = self.instance.user
        if author != request.user:
            messages.error(request, 'You are not allowed to update this post', 'danger')
            return redirect(self.instance.get_absolute_url())
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, slug):
        form = self.form_class(instance=self.instance)
        return render(request, self.template_name, {'form': form})

    def post(self, request, slug):
        form = self.form_class(request.POST, request.FILES, instance=self.instance)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Post updated successfully', 'success')
            return redirect(post.get_absolute_url())
        return render(request, self.template_name, {'form': form})


class CommentReplyView(LoginRequiredMixin , View):
    form_class = CommentReplyForm

    def post(self, request, post_slug, comment_id):
        form = self.form_class(request.POST)
        post_instance = get_object_or_404(Post, slug=post_slug)
        if form.is_valid():
            cm = form.save(commit=False)
            cm.user = request.user
            cm.post = post_instance
            cm.reply = get_object_or_404(Comment, id=comment_id)
            cm.is_reply = True
            cm.save()
            messages.success(request, 'Comment created successfully', 'success')
            return redirect(post_instance.get_absolute_url())
        return render(request, 'social/detail.html', {'form':form})


class LikePostView(LoginRequiredMixin , View):

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user == self.post_instance.user:
            raise ValidationError('You cant like yourself')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        like = Like.objects.filter(user=request.user, post=self.post_instance)
        if not like.exists():
            Like.objects.create(user=request.user, post=self.post_instance)
        else:
            like.delete()
        return redirect(self.post_instance.get_absolute_url())

social/templates/social/create_post.html
{% load static %}
{% include 'social/inc/header.html' %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
		<!-- start banner Area -->
		<section class="relative about-banner">
			<div class="overlay overlay-bg"></div>
			<div class="container">
				<div class="row d-flex align-items-center justify-content-center">
					<div class="about-content col-lg-12">
						<h1 class="text-white">
							Create Post
						</h1>
						<p class="text-white link-nav"><a href="{% url 'social:home' %}">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="{% url 'social:post_create' %}"> Create post</a></p>
					</div>
				</div>
			</div>
		</section>
		<!-- End banner Area -->

		<!-- Start contact-page Area -->
		<section class="contact-page-area section-gap">
			<div class="container">
				{% include 'social/inc/messages.html' %}
				<p class="fieldWrapper">{{form.title.errors}}</p>
				<div class="row">
					<div class="col-lg-8">
						<form class="form-area contact-form text-right" action="#" method="post" enctype="multipart/form-data"> {% csrf_token %}
							<div class="row">
								<div class="col-md-6 form-group">
									<input name="title" placeholder="Enter post title" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required="" type="text">
									<textarea class="common-textarea form-control" name="body" placeholder="Enter Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>
									{{form.img}}
									<button class="genric-btn primary" style="float: left;" type="submit">Submit Post</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>
		<!-- End contact-page Area -->

		{% include 'social/inc/footer.html' %}
	</body>
	</html>

social/templates/social/detail.html
{% load static %}
{% include 'social/inc/header.html' %}
{% load humanize %}
{% load inclusion_tags %}


<!-- start banner Area -->
	<section class="relative about-banner">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<p class="text-white link-nav"><a href="{% url 'social:home' %}">Home </a> <span class="lnr lnr-arrow-right"></span> <a href="{{ post.get_absolute_url }}"> {{post.title|truncatewords:4}}</a></p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- Start post-content Area -->
	<section class="post-content-area single-post-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 posts-list">
					<div class="single-post row">
						<div class="col-lg-12">
							<div class="feature-img">
								<img class="img-fluid" src={{post.img.url}} alt="">
							</div>
						</div>
						<div class="col-lg-3  col-md-3 meta-details">
							<div class="user-details row">
								<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'social:profile' request.user.username %}">{{post.user.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
								<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.created|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
								<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.like_count}} Likes</a> <span class="lnr lnr-thumbs-up"></span></p>
								<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{post.postcm.count}} Comments</a> <span class="lnr lnr-bubble"></span></p>

							</div>
						</div>
						<div class="col-lg-9 col-md-9">
							<h3 class="mt-20 mb-20">{{post.title}}</h3>
							{% if request.user == post.user %}
							<a class="btn btn-danger" href="{% url 'social:post_delete' post.slug %}">Delete post</a>
							<a class="btn btn-info" href="{% url 'social:post_update' post.slug %}">Update post</a>
							{% else %}
							{% if not like_existance %}
							<a class="btn btn-info" href="{% url 'social:like_post' post.slug %}">Like</a>
							{% else %}
							<a class="btn btn-danger" href="{% url 'social:like_post' post.slug %}">UnLike</a>
							{% endif %}
							{% endif %}
								<p class="excert">
								{{post.body|safe|linebreaks}}
							</p>
						</div>
					</div>
					<div class="comments-area">
						<h4>{{post.postcm.count}} Comments</h4>
						{% for cm in post.postcm.all %}
						{% if not cm.is_reply %}
						<div class="comment-list">
							<div class="single-comment justify-content-between d-flex">
								<div class="user justify-content-between d-flex">
									<div class="thumb">
										<img style="max-width: 80px;" src="{{cm.user.img.url}}" alt="">
									</div>
									<div class="desc">
										<h5><a href="{% url 'social:profile' cm.user.username %}">{{cm.user.get_full_name}}</a></h5>
										<p class="date">{{cm.created|date:"d M Y"}} </p>
										<p class="comment">
											{{cm.body|safe}}
										</p>
										<form method="post" action="{% url 'social:cmreply' post.slug cm.id %}"> {% csrf_token %}
											<div class="form-group">
												<textarea class="form-control mb-10" rows="5" name="body" placeholder="Body" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
											</div>
											<div class="reply-btn">
												<button type="submit" class="btn btn-danger text-uppercase">Reply</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
						{% for reply in cm.replies.all %}
						<div class="comment-list left-padding">
							<div class="single-comment justify-content-between d-flex">
								<div class="user justify-content-between d-flex">
									<div class="thumb">
										<img style="max-width: 80px;" src="{{reply.user.img.url}}" alt="">
									</div>
									<div class="desc">
										<h5><a href="{% url 'social:profile' reply.user.username %}">{{reply.user.get_full_name}}</a></h5>
										<p class="date">{{reply.created|date:"d M Y"}}  </p>
										<p class="comment">
											{{reply.body|safe}}
										</p>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
						{% endif %}
						{% empty %}
							No comments at the moment. Be the first one!
						{% endfor %}
					</div>
					<div class="comment-form">
						<h4>Leave a Comment</h4>
						{% include 'social/inc/messages.html' %}
						<form method="post" > {% csrf_token %}
							<div class="form-group">
								<textarea class="form-control mb-10" rows="5" name="body" placeholder="Body" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
							</div>
							<button type="submit" class="primary-btn text-uppercase">Post Comment</button>
						</form>
					</div>
				</div>
				<div class="col-lg-4 sidebar-widgets">
					<div class="widget-wrap">
						{% latest_post %}
						{% include 'social/inc/widget-search.html' %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End post-content Area -->

	{% include 'social/inc/footer.html' %}


</body>
</html>

social/templates/social/home.html
{% load static %}
{% include 'social/inc/header.html' %}
{% load humanize %}
{% load inclusion_tags %}

<!-- start banner Area -->
	<section class="banner-area relative blog-home-banner" id="home">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content blog-header-content col-lg-12">
					<h1 class="text-white">
						Welcome to My Django Social Network <br> {% if request.user.get_short_name %}{{request.user.get_short_name}}{% endif %}
					</h1>
					<p class="text-white">
						Here you can find a social network for Python, Django and all needed to become a Backend-Developer
					</p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- Start top-category-widget Area -->
	<section class="top-category-widget-area pt-90 pb-90 ">
		<div class="container">
		</div>
		<div style="text-align: center; width: 300px; margin: auto; background-color: #f9f9ff;">{% include 'social/inc/messages.html' %}</div>
	</section>
	<!-- End top-category-widget Area -->

	<!-- Start post-content Area -->
	<section class="post-content-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 posts-list">
					{% for post in posts %}
					<div class="single-post row">
						<div class="col-lg-3  col-md-3 meta-details">
							<div class="user-details row">
								<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'social:profile' post.user.username %}">{{post.user.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
								<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.created|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
								<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.like_count}} Likes</a> <span class="lnr lnr-thumbs-up"></span></p>
								<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{post.postcm.count}} Comments</a> <span class="lnr lnr-bubble"></span></p>
							</div>
						</div>
						<div class="col-lg-9 col-md-9 ">
							<div class="feature-img">
								<img class="img-fluid" src= {{post.img.url}} alt="">
							</div>
							<a class="posts-title" href="{{ post.get_absolute_url }}"><h3>{{post.title}}</h3></a>
							<p class="excert">
								{{post.body|truncatewords:40|safe}}
							</p>
							<a href="{{ post.get_absolute_url }}" class="primary-btn">View More</a>
						</div>
					</div>
					{% empty %}
					<h3> No posts at the moment </h3>
					{% endfor %}
					<nav class="blog-pagination justify-content-center d-flex">
						<ul class="pagination">
							{% if posts.has_previous %}
							<li class="page-item">
								{% if request.GET.q %}
									<a href="?page={{posts.previous_page_number}}&q={{ request.GET.q }}" class="page-link" aria-label="Previous">
								{% else %}
									<a href="{% url 'social:home' posts.previous_page_number %}" class="page-link" aria-label="Previous">
								{% endif %}
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-left"></span>
									</span>
								</a>
							</li>
							{% endif %}
							{% if posts %}
							{% for i in posts.paginator.page_range %}
								{% if posts.number == i %}
								<li class="page-item active"><a href="#" class="page-link">{{i}}</a></li>
								{% else %}
									{% if request.GET.q %}
										<li class="page-item"><a href="?page={{ i }}&q={{ request.GET.q }}" class="page-link">{{ i }}</a></li>
									{% else %}
										<li class="page-item"><a href="{% url 'social:home' i %}" class="page-link">{{ i }}</a></li>
									{% endif %}
								{% endif %}
							{% endfor %}
							{% if posts.has_next %}
							<li class="page-item">
								{% if request.GET.q %}
								<a href="?page={{posts.next_page_number}}&q={{ request.GET.q }}" class="page-link" aria-label="Previous">
								{% else %}
								<a href="{% url 'social:home' posts.next_page_number %}" class="page-link" aria-label="Next">
								{% endif %}
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-right"></span>
									</span>
								</a>
							</li>
							{% endif %}
							{% endif %}
						</ul>
					</nav>
				</div>
				<div class="col-lg-4 sidebar-widgets">
					<div class="widget-wrap">
						{% latest_post %}
						{% include 'social/inc/widget-search.html' %}
					</div>
			</div>
		</div>
	</section>
	<!-- End post-content Area -->
	{% include 'social/inc/footer.html' %}

</body>
</html>

social/templates/social/profile.html
{% load static %}
{% include 'social/inc/header.html' %}
{% load humanize %}
{% load inclusion_tags %}


<!-- start banner Area -->
	<section class="banner-area relative blog-home-banner" id="home">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content blog-header-content col-lg-12">
					<h1 class="text-white">
						Welcome to My Django Social Network <br> {% if request.user.get_short_name %}{{request.user.get_short_name}}{% endif %}
					</h1>
					<p class="text-white">
						Here you can find a social network for Python, Django and all needed to become a Backend-Developer
					</p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- Start top-category-widget Area -->
	<section class="top-category-widget-area pt-90 pb-90 ">
		<div class="container">
		</div>
		<div style="text-align: center; width: 300px; margin: auto; background-color: #f9f9ff;">{% include 'social/inc/messages.html' %}</div>
	</section>
	<!-- End top-category-widget Area -->

	<!-- Start post-content Area -->
	<section class="post-content-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 posts-list">
					{% for post in posts %}
					<div class="single-post row">
						<div class="col-lg-3  col-md-3 meta-details">
							<div class="user-details row">
								<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'social:profile' user.username %}">{{post.user.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
								<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.created|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
								<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.like_count}} Likes</a> <span class="lnr lnr-thumbs-up"></span></p>
								<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{post.postcm.count}} Comments</a> <span class="lnr lnr-bubble"></span></p>
							</div>
						</div>
						<div class="col-lg-9 col-md-9 ">
							<div class="feature-img">
								<img class="img-fluid" src= {{post.img.url}} alt="">
							</div>
							<a class="posts-title" href="{{ post.get_absolute_url }}"><h3>{{post.title}}</h3></a>
							<p class="excert">
								{{post.body|truncatewords:40|safe}}
							</p>
							<a href="{{ post.get_absolute_url }}" class="primary-btn">View More</a>
						</div>
					</div>
					{% empty %}
					<h3> No posts at the moment </h3>
					{% endfor %}
				</div>
				<div class="col-lg-4 sidebar-widgets">
					<div class="widget-wrap">
						{% include 'social/inc/widget-writer.html' %}
						{% latest_post %}
						{% include 'social/inc/widget-search.html' %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End post-content Area -->
	{% include 'social/inc/footer.html' %}

</body>
</html>

social/templates/social/update_post.html
{% load static %}
{% include 'social/inc/header.html' %}

		<!-- start banner Area -->
		<section class="relative about-banner">
			<div class="overlay overlay-bg"></div>
			<div class="container">
				<div class="row d-flex align-items-center justify-content-center">
					<div class="about-content col-lg-12">
						<h1 class="text-white">
							Update Post
						</h1>
						<p class="text-white link-nav"><a href="#">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="#"> Update post</a></p>
					</div>
				</div>
			</div>
		</section>
		<!-- End banner Area -->

		<!-- Start contact-page Area -->
		<section class="contact-page-area section-gap">
			<div class="container">
				{% include 'social/inc/messages.html' %}
				<p>{{form.title.errors}}</p>
				<div class="row">
					<div>
						<form class="form-area" action="#" method="post" enctype="multipart/form-data"> {% csrf_token %}
							<div class="row">
								<div class="col-lg-8 form-group">
									{{form.as_p}}
									<button class="genric-btn primary" style="float: left;" type="submit">Submit Post</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>
		<!-- End contact-page Area -->

		{% include 'social/inc/footer.html' %}
	</body>
	</html>